CREATE TABLE USER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(15),
    PASSWORD VARCHAR(500),
    EMAIL VARCHAR(40),
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30)
);

CREATE TABLE  SENSOR_OBSERVATION(
    ID BIGINT AUTO_INCREMENT,
    temperature DOUBLE,
    gyroscope DOUBLE,
    accelerometer DOUBLE,
    magnetometer DOUBLE,
    pressure DOUBLE,
    humidity DOUBLE
);

CREATE TABLE NAVIGATION(
    ID BIGINT AUTO_INCREMENT,
    DIRECTION VARCHAR(10)
);